name: example
description: Example for virtual_statics
version: 1.0.0
repository: https://github.com/benthillerkus/virtual_statics
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  virtual_statics: ^0.0.2

dev_dependencies:
  virtual_statics_builder: ^0.0.2
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.12
