name: virtual_statics_builder
description: Overwrite static fields on sealed classes in Dart (using a generated companion enum).
version: 0.0.1
repository: https://github.com/benthillerkus/virtual_statics

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^6.8.0
  build: ^2.4.1
  source_gen: ^1.5.0
  virtual_statics: ^1.0.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  lints: ^4.0.0
  test: ^1.24.0
