name: virtual_statics
repository: https://github.com/benthillerkus/virtual_statics
packages:
  - annotations
  - generator
  - example
  - .

command:
  bootstrap:
    environment:
      sdk: ">= 3.0.0 <4.0.0"
    dev_dependencies:
      lints: ^4.0.0
      test: ^1.24.0
      build_runner: ^2.4.12

scripts:
  build:
    exec: dart run build_runner build
    packageFilters:
      scope: example
