name: virtual_statics
description: Annotations for package:virtual_statics
version: 1.0.0
repository: https://github.com/benthillerkus/virtual_statics

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  meta: ^1.15.0
